### ISSUE TITLE
规则里的 C 代表什么？

### ISSUE THREAD

**Issue by ZenonHuang** [hellowingy/wingy-announcement#47]
如您在自定义配置里所言：
>criteria中的p,k,s,r分别表示 prefix (前缀)，keyword(关键词),suffix(后缀),regex(正则表达式)

我却在配置文件里看到 ：
``` 
- c,stat.youku.com
```
这样的规则， c 是代表什么？

**Comment by kimanlo** [comment]
针对域名，例： - c,abc.ddd.com
只对abc.ddd.com/a/b/c.html , abc.ddd.com/***** 的内容，和 suffix有区别

**Comment by ZenonHuang** [comment]
谢谢您的解答
