### ISSUE TITLE
请问下，在ios客户端，自定义配置怎么删除？谢谢

### ISSUE THREAD

**Issue by github1510** [hellowingy/wingy-announcement#49]

**Comment by kimanlo** [comment]
在手机端删除，iCloud就会同步删除的。

**Comment by github1510** [comment]
我就是不知道怎么在手机上删除，悲催。。。。长按，又滑cell都不行

**Comment by kimanlo** [comment]
@github1510  
你要进入自定义配置，里面有删除配置的选项的。

**Comment by github1510** [comment]
ok，找到了，谢谢
PS：有个建议，收费版的下架可能会让一些老用户感觉不爽，花了钱的东西反而没有保障；surge的作者因为经常变动价格而被骂，也有这方面的原因。

**Comment by kimanlo** [comment]
@github1510  Wingy下架了吗？
