### ISSUE TITLE
PC端其他软件如何达成内置规则的效果

### ISSUE THREAD

**Issue by Jay54520** [hellowingy/wingy-announcement#55]
我认为你的 [SmartConf](https://github.com/hellowingy/wingy-announcement/blob/master/Smart.conf) 很智能，但不知如何在 PC 端实现类似的效果。  

1. 工作时需要访问内网，所以不能用全局模式；
1. Shadowsocks 的自动模式需要手动添加网址，添加不过来

我先在的方式是，访问内网时切回自动模式，其他情况使用全局模式。

**Comment by kimanlo** [comment]
电脑就用SS(R)吧，选择PAC模式，然后更新相应的模式就可以达到你说的效果了。

**Comment by mutedstack** [comment]
@kimanlo 
能否给出例子或者相关教程，我现在 PAC 的做法就是增加域名规则
```
var proxy = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;";
var rules = [];
...
```

**Comment by mutedstack** [comment]
查找了一下 PAC 的规则
> 通配符支持。比如 *.example.com/* 实际书写时可省略 * ， 如.example.com/ ， 和 *.example.com/* 效果一样
例外规则 @@ ，如 @@*.example.com/* 满足 @@ 后规则的地址不使用代理

所以我现在规则是这样
```
var rules = [
  "@@*.内网.com/*",
  "*",
  ......
]
```
除了内网，全部走 socks5。

之后可以加入常用国内网站的例外，比如taobao, jd 等等。
