### ISSUE TITLE
关于 v1.1.0 build:1610261 自定规则的一些想法

### ISSUE THREAD

**Issue by ChengLuffy** [hellowingy/wingy-announcement#7]
各功能测试正常。
关于 **自定规则的一些想法**：
1. 配置文件错误时，只是不能链接成功，如果有相应的 _弹窗`Alert`_ 帮助定位错误信息更好。
2. 即使手机端的编辑器再好，和电脑端比较还是不方便，建议添加 **url 导入/ UTI 文件类型支持/iCloud 同步配置文件**；**Supported iCloud Drives**
3. 是否支持 **主配置文件和各相应规则文件** 分离，类似 `SpechtLite` 的配置文件形式，如支持路径如何填写？
4. `IPv6` 在 `iplist` 应该以怎样的形式填写？同时由于 `IPv6` 的特殊性，目前 `wingy` 对其处理的策略是全部 **reject** 还是？
5. iPhone6、iOS10.1、自定义规则、多节点（3个）、 浏览网页有频繁断线情况。**Fixed**
6. 更改时保存备注 **同名** 不可保存。**Fixed**
7. 在 `iplist` 加入 `telegram` 的 IP 段后，`telegram` 出现持续 **updating**。**Fixed**

感谢🙏

---
update 16.12.12，v1.1.3 Build:1612101
断线情况解决，`speed` 正常使用。

**Comment by zspsky** [comment]
5.iPhone6、iOS10.1、自定义规则、多节点（3个）、 浏览网页有频繁断线情况。
我也有同样的情况

**Comment by kimanlo** [comment]
speed慎用~

**Comment by ChengLuffy** [comment]
`speed` 规则目前由于线程过多问题会崩溃，这个问题慢慢等解决了，一个节点或者分多节点分别代理不同的规则可行。

**Comment by zspsky** [comment]
speed可以改一下，改成定时检测如10分钟检查一次。在期间使用速度最快的那个。

**Comment by ChengLuffy** [comment]
@zspsky 这个。。。`wingy` 基于 [NEKit](https://github.com/zhuhaow/NEKit) , `speed` 也是 `NEKit` 的一个特性，`NEKit`作者曾经说，等不忙会解决这个问题。
